defaults:
  - default.yaml

sft_config:
  num_train_epochs: 10
  weight_decay: 0.01
  eval_strategy: "epoch"
  #eval_steps: 1000
  #save_steps: 1000
  per_device_eval_batch_size: 16
  load_best_model_at_end: True
  metric_for_best_model: "eval_loss"
  lr_scheduler_type: "cosine"
  

dataset: ???
tags: [sft, health, keywords]
adapters_paths: lora/
