defaults:
  - default.yaml

sft_config:
  num_train_epochs: 1
  eval_strategy: "epoch"
  load_best_model_at_end: True
  metric_for_best_model: "eval_loss"
  

#dataset: datasets/health/model=xz97-AlpaCare-llama2-13b_t=0.7_size=60000/public_seed.parquet
dataset: datasets/health/sft/sft_dataset.parquet
tags: [sft, health]
adapters_paths: lora/
