name: synth-kg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
    - absl-py==2.3.1
    - accelerate==1.7.0
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.12
    - aiohttp-cors==0.7.0
    - aioprometheus==23.12.0
    - aiosignal==1.3.2
    - airportsdata==20250523
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - astor==0.8.1
    - asttokens==3.0.0
    - attrs==25.3.0
    - audioread==3.0.1
    - beautifulsoup4==4.13.4
    - bitsandbytes==0.46.0
    - blake3==1.0.5
    - blis==1.2.0
    - bs4==0.0.2
    - cachetools==5.5.2
    - catalogue==2.0.10
    - certifi==2025.4.26
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - click==8.2.1
    - cloudpathlib==0.20.0
    - cloudpickle==3.1.1
    - colorful==0.5.6
    - comm==0.2.2
    - compressed-tensors==0.10.2
    - confection==0.1.5
    - cupy-cuda12x==13.4.1
    - cymem==2.0.11
    - datasets==3.3.2
    - debugpy==1.8.14
    - decorator==5.2.1
    - depyf==0.18.0
    - dill==0.3.8
    - diskcache==5.6.3
    - distlib==0.3.9
    - distro==1.9.0
    - dnspython==2.7.0
    - docker-pycreds==0.4.0
    - einops==0.8.1
    - email-validator==2.2.0
    - evaluate==0.4.3
    - executing==2.2.0
    - fastapi==0.115.12
    - fastapi-cli==0.0.7
    - fastrlock==0.8.3
    - ffmpy==0.5.0
    - filelock==3.18.0
    - frozenlist==1.7.0
    - fsspec==2024.12.0
    - gguf==0.17.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-api-core==2.24.1
    - google-auth==2.38.0
    - googleapis-common-protos==1.69.1
    - gradio==5.31.0
    - gradio-client==1.10.1
    - greenlet==3.2.2
    - groovy==0.1.2
    - grpcio==1.70.0
    - h11==0.16.0
    - hf-xet==1.1.3
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - huggingface-hub==0.33.0
    - hydra-core==1.3.2
    - idna==3.10
    - importlib-metadata==8.7.0
    - interegular==0.3.3
    - ipykernel==6.29.5
    - ipython==9.2.0
    - ipython-pygments-lexers==1.1.1
    - jedi==0.19.2
    - jinja2==3.1.6
    - jiter==0.10.0
    - jiwer==3.1.0
    - joblib==1.4.2
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - langcodes==3.5.0
    - language-data==1.3.0
    - lark==1.2.2
    - lazy-loader==0.4
    - leveldb==0.201
    - librosa==0.11.0
    - linkify-it-py==2.0.3
    - llguidance==0.7.29
    - llvmlite==0.44.0
    - lm-format-enforcer==0.10.11
    - marisa-trie==1.2.1
    - markdown==3.8.2
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib-inline==0.1.7
    - mdit-py-plugins==0.4.2
    - mdurl==0.1.2
    - memray==1.16.0
    - mistral-common==1.8.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgspec==0.19.0
    - multidict==6.4.4
    - multiprocess==0.70.16
    - murmurhash==1.0.12
    - nest-asyncio==1.6.0
    - networkx==3.5
    - ninja==1.11.1.4
    - nltk==3.9.1
    - nodeenv==1.9.1
    - numba==0.61.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-ml-py==12.570.86
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - omegaconf==2.3.0
    - openai==1.86.0
    - opencensus==0.11.4
    - opencensus-context==0.1.3
    - opencv-python-headless==4.11.0.86
    - opentelemetry-api==1.34.1
    - opentelemetry-exporter-otlp==1.34.1
    - opentelemetry-exporter-otlp-proto-common==1.34.1
    - opentelemetry-exporter-otlp-proto-grpc==1.34.1
    - opentelemetry-exporter-otlp-proto-http==1.34.1
    - opentelemetry-exporter-prometheus==0.55b1
    - opentelemetry-proto==1.34.1
    - opentelemetry-sdk==1.34.1
    - opentelemetry-semantic-conventions==0.55b1
    - opentelemetry-semantic-conventions-ai==0.4.9
    - orjson==3.10.18
    - outlines==0.1.11
    - outlines-core==0.1.26
    - packaging==25.0
    - pandas==2.3.0
    - parso==0.8.4
    - partial-json-parser==0.2.1.1.post5
    - peft==0.16.0
    - pexpect==4.9.0
    - pillow==11.2.1
    - platformdirs==4.3.6
    - pooch==1.8.2
    - preshed==3.0.9
    - prometheus-client==0.22.1
    - prometheus-fastapi-instrumentator==7.1.0
    - prompt-toolkit==3.0.51
    - propcache==0.3.2
    - proto-plus==1.26.0
    - protobuf==5.29.5
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - py-spy==0.4.0
    - pyarrow==19.0.1
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybase64==1.4.1
    - pycountry==24.6.1
    - pycparser==2.22
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pydantic-extra-types==2.10.5
    - pydub==0.25.1
    - pygments==2.19.1
    - pynvim==0.5.2
    - pyright==1.1.399
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - python-json-logger==3.3.0
    - python-multipart==0.0.20
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==26.4.0
    - quantile-python==1.1
    - rapidfuzz==3.13.0
    - ray==2.47.0
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.4
    - rich==14.0.0
    - rich-toolkit==0.14.7
    - rpds-py==0.25.1
    - rsa==4.9
    - ruff==0.11.11
    - safehttpx==0.1.6
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - semantic-version==2.10.0
    - sentence-transformers==3.4.1
    - sentencepiece==0.2.0
    - sentry-sdk==2.22.0
    - setproctitle==1.3.5
    - shellingham==1.5.4
    - six==1.17.0
    - smart-open==7.1.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soundfile==0.13.1
    - soupsieve==2.7
    - soxr==0.5.0.post1
    - spacy==3.8.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.5.1
    - stack-data==0.6.3
    - starlette==0.46.2
    - sympy==1.14.0
    - tensorboard-data-server==0.7.2
    - textual==2.1.2
    - thinc==8.3.4
    - threadpoolctl==3.5.0
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - tomlkit==0.13.2
    - torch==2.7.0
    - torchaudio==2.7.0
    - torchvision==0.22.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.52.4
    - triton
    - trl==0.15.2
    - typer==0.16.0
    - typing-extensions==4.14.0
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - uc-micro-py==1.0.3
    - unidecode==1.3.8
    - urllib3==2.4.0
    - uvicorn==0.34.3
    - uvloop==0.21.0
    - virtualenv==20.29.3
    - visidata==3.1.1
    - vllm==0.9.2
    - wandb==0.19.7
    - wasabi==1.1.3
    - watchfiles==1.0.5
    - wcwidth==0.2.13
    - weasel==0.4.1
    - websockets==15.0.1
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xformers==0.0.30
    - xgrammar==0.1.19
    - xxhash==3.5.0
    - yarl==1.20.1
    - zipp==3.23.0
